"""
Django settings for publ project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path
import requests
import subprocess
import socket
import django

# Helper function for GCP metadata
def get_meta(entry):
  METADATA_URL = 'http://metadata.google.internal/computeMetadata/v1/instance' + entry
  METADATA_HEADERS = {'Metadata-Flavor': 'Google'}
  r = requests.get(METADATA_URL, headers=METADATA_HEADERS)
  return r.text
DEBUG = True

if DEBUG:
    # Build paths inside the project like this: BASE_DIR / 'subdir'.
    #BASE_DIR = Path(__file__).resolve().parent.parent
    BASE_DIR = os.path.dirname(os.path.abspath(__file__))
else:
    BASE_DIR = '/var/lib/django/research'
    SITE_ROOT = os.path.dirname(os.path.abspath(__file__))
    DJANGO_ROOT = os.path.dirname(os.path.realpath(django.__file__))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+_=qb2^hit1f@_jrbq0ue=62%^me$6dhpp_s6vo200=^ahz(nh'

# SECURITY WARNING: don't run with debug turned on in production!
internal_ip = 'localhost'
if not DEBUG:
    internal_ip = socket.gethostbyname(socket.gethostname())
ALLOWED_HOSTS = ['research.unemi.edu.ec', '127.0.0.1', internal_ip]


# Application definition

INSTALLED_APPS = [
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'publ',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

SITE_ROOT = os.path.dirname(os.path.abspath(__file__))

ROOT_URLCONF = 'publ.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(SITE_ROOT, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
print(os.path.join(SITE_ROOT, 'templates'))
TIEMPO_CIERRE_SESION = 1800
ADMINISTRADOR_ID = 1
# CEDULA COMO CLAVE DE USUARIO
CLAVE_USUARIO_CEDULA = True
EMAIL_DOMAIN = 'unemi.edu.ec'
NOMBRE_INSTITUCION = "Universidad Estatal de Milagro"

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
ASGI_APPLICATION = "publ.asgi.application"
WSGI_APPLICATION = "publ.wsgi.application"
PUSUARIO = 'postgres'
if not DEBUG:
    PIP = '10.68.1.239'
    PBD = 'sistemagestion'
    PPASW = 'L0eMnR[FyS^M;uvX'
else:
    PIP = '127.0.0.1'
    PBD = 'sga'
    PPASW = '12345'
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'research',  # Or path to database file if using sqlite3. #sga29
        'USER': 'postgres',  # Not used with sqlite3.
        'PASSWORD': '12345',  # Not used with sqlite3.
        'HOST': 'localhost',  # Set to empty string for localhost. Not used with sqlite3.
        'PORT': '5432',  # Set to empty string for default. Not used with sqlite3.
    },
    'sga': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': PBD,  # Or path to database file if using sqlite3.
        'USER': PUSUARIO,  # Not used with sqlite3.
        'PASSWORD': PPASW,  # Not used with sqlite3.
        'HOST': PIP,  # Set to empty string for localhost. Not used with sqlite3.
        'PORT': '5432',  # Set to empty str
    },
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-EC'

TIME_ZONE = 'America/Guayaquil'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
if DEBUG:
    STATICFILES_DIRS = [
        os.path.join(BASE_DIR, 'static'),
    ]
else:
    STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

STATIC_URL = '/static/'

print("La ruta de BASE_DIR es:", BASE_DIR)


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = [
    'https://research.unemi.edu.ec',
]

CORS_ALLOWED_ORIGIN_REGEXES = [
    'https://research.unemi.edu.ec',
]

CORS_ORIGIN_WHITELIST = [
    'https://research.unemi.edu.ec',
]

CSRF_TRUSTED_ORIGINS = [
    'https://research.unemi.edu.ec',
]

if DEBUG:
    LOCALES = ['http://localhost',
               'http://127.0.0.1',
               'http://127.0.0.1:8002',
               'http://127.0.0.1:8002'
               ]

    CORS_ALLOWED_ORIGINS += LOCALES
    CORS_ALLOWED_ORIGIN_REGEXES += LOCALES
    CORS_ORIGIN_WHITELIST += LOCALES
    CSRF_TRUSTED_ORIGINS += LOCALES
# # Daphne

NAMECONEXION='sga'
CACHE_MIDDLEWARE_ALIAS = 'default'
CACHE_MIDDLEWARE_SECONDS = 3600  # Duración de la caché en segundos
CACHE_MIDDLEWARE_KEY_PREFIX = 'research_'

USER_AGENTS_CACHE = 'default'
BASE_CONEXION = (
    (1, u'research'),
)
